### ISSUE TITLE
Verify JWT, should not access database

### ISSUE THREAD

**Issue by ducvo-kms** [MinhQuan992/smarter-backend#1]
https://github.com/MinhQuan992/smarter-backend/blob/fbe0944746ce79cf42cae63ca261a394e59350eb/src/main/java/com/example/smarterbackend/filter/CustomAuthorizationFilter.java#L39

**Comment by MinhQuan992** [comment]
Thanks, brother @ducvo-kms. I have changed the way to get roles from the JWT.
